# Generated by Django 5.2.4 on 2025-08-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_alter_pen_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('pen_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.penmodel')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
