# Generated by Django 5.2.4 on 2025-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='colour',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
