# Generated by Django 5.2.4 on 2025-08-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_penpartsusage_quantity_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_incurred', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('SHIPPING', 'Shipping Supplies'), ('TOOLS', 'Tools'), ('FEES', 'eBay Fees'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateField()),
                ('final_sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('other_fees', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.pen')),
            ],
        ),
    ]
