# Generated by Django 5.2.4 on 2025-08-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sale',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0.61, max_digits=8),
        ),
    ]
