# Generated by Django 5.2.4 on 2025-09-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_expense_description_alter_sale_other_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=8),
        ),
    ]
