# Generated by Django 5.2.4 on 2025-08-04 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=100)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acquisition_date', models.DateField()),
                ('ebay_item_id', models.CharField(blank=True, max_length=20, null=True)),
                ('refurb_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('UNDER_REFURB', 'Under Refurbishment'), ('LISTED', 'Listed'), ('SOLD', 'Sold')], default='IN_STOCK', max_length=20)),
                ('pen_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.penmodel')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
        ),
    ]
