# Generated by Django 5.2.4 on 2025-08-05 15:20

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penmodel',
            options={'ordering': ['brand', django.db.models.functions.text.Length('name'), 'name']},
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity_on_hand', models.IntegerField()),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('pen_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.penmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PenPartsUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.part')),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pen')),
            ],
        ),
    ]
