# Generated by Django 5.2.4 on 2025-08-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_penmodel_options_part_penpartsusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='penpartsusage',
            name='cost_at_time_of_use',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
