# Generated by Django 5.2.4 on 2025-08-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_penpartsusage_cost_at_time_of_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penpartsusage',
            name='quantity_used',
            field=models.IntegerField(default=1),
        ),
    ]
