# Generated by Django 5.2.4 on 2025-08-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_penpartsusage_quantity_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penpartsusage',
            name='pen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='inventory.pen'),
        ),
    ]
