# Generated by Django 5.2.4 on 2025-08-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_penpartsusage_pen'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='colour',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
