# Generated by Django 5.2.4 on 2025-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_part_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pen',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('UNDER_REFURB', 'Under Refurbishment'), ('AWAITING_PARTS', 'Awaiting Parts'), ('LISTED', 'Listed'), ('SOLD', 'Sold')], default='IN_STOCK', max_length=20),
        ),
    ]
