# Generated by Django 5.2.4 on 2025-09-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_pen_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='part',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='part',
            name='pen_model',
        ),
        migrations.AlterField(
            model_name='part',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
